name: CI

on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t  JTMassa/my-portfolio  .

      
      - name: Push image
        run: |
            docker login -u JTMassa -p $ {{secrets.REGISTRY_PASS}}
            docker push JTMassa/my-portfolio
          
